POST http://localhost:3000/api/selectCategory
Content-Type: application/json

{
    "title": "Purchase a budget managing app"
}
###

POST http://localhost:3000/api/signups
Content-Type: application/json

{
    "username": "xz",
    "email":"xz@yahoo.com",
    "password":"xz@123",
    "confirmPassword":"xz@123"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"xz@yahoo.com",
    "password":"xz@123"
}


### Create Goal
POST http://localhost:3000/api/goals
Content-Type: application/json

{
  "title": "New Goal Test",
  "target": 10000,
  "saved": 2000,
  "deadline": "2025-12-12"
}

### Get All Goals
GET http://localhost:3000/api/goals

### Update Goal
PUT http://localhost:3000/api/goals/692bf9220e86b30dcb45a059
Content-Type: application/json

{
  "title": "Updated Goal",
  "target": 12000,
  "saved": 5000,
  "deadline": "2025-12-25"
}

### Delete Goal
DELETE http://localhost:3000/api/goals/692bf9220e86b30dcb45a059


# date: {
#     type: Date,
#     required: true,
#   },
#   merchant: {
#     type: String,
#     required: true,
#   },
#   category: {
#     categoryName: {
#       type: String,
#       required: true,
#     },
#     categoryColor: {
#       type: String,
#       required: true,
#     },
#   },
#   amount: {
#     type: Number,
#     required: true,
#   },
#   userId: {
#     type: mongoose.Schema.Types.ObjectId,
#     required: true,
#     ref: "User",
#   },
###
POST http://localhost:3000/api/transactions
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzE3Y2M0MTQ0OTczN2Q3MjY0OTAxMCIsImVtYWlsIjoieHpAeWFob28uY29tIiwiaWF0IjoxNzY0ODUwOTEzLCJleHAiOjE3NjU0NTU3MTN9.MFdAibf7_kjPiZ6-PUgd_cpmLeEf0GoG4h3p2Qpyf2Q

{
  "date": "2025-12-04T12:24:39.289Z",
  "merchant": "asdf",
  "category": {
    "categoryName": "1234",
    "categoryColor": "Red"
  },
  "amount": 123
}





